name: My Python Custom Action
description: Python composite action (cross-runner)
inputs:
  message:
    description: 'Message to process'
    required: false
    default: 'Hello from Python custom action!'
runs:
  using: 'composite'
  steps:
    - name: init
      shell: bash
      run: |
        pip install -r requirements.txt

    - name: Run Python action
      shell: bash
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      run: |
        python3 src/main.py
