name: 'My Python Custom Action'

description: 'A custom GitHub Action written in Python for reusable workflows'

inputs:
  message:
    description: 'The message to process'
    required: false
    default: 'Hello from Python custom action!'

outputs:
  result:
    description: 'The processed message'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'cpu'
  color: 'green'