name: actions-test
description: Demo composite action for this runner
inputs:
  message:
    description: Message to print
    required: false
    default: "hello"
runs:
  using: composite
  steps:
    - name: Print Message
      shell: bash
      run: |
        echo "From actions-test: ${INPUT_MESSAGE}"
