name: 'My Python Custom Action'

description: 'A custom GitHub Action written in Python for reusable workflows'

inputs:
  message:
    description: 'The message to process'
    required: false
    default: 'Hello from Python custom action!'

outputs:
  result:
    description: 'The processed message'

runs:
  using: 'python3'
  main: 'src/main.py'

branding:
  icon: 'cpu'
  color: 'green'