name: My Python Custom Action
description: Python composite action (cross-runner)
inputs:
  message:
    description: 'Message to process'
    required: false
    default: 'Hello from Python custom action!'
runs:
  using: 'composite'
  steps:
    - name: Run Python action
      shell: sh
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      run: |
        if [ -n "${GITHUB_ACTION_PATH}" ]; then
          ACTION_DIR="${GITHUB_ACTION_PATH}"
        else
          ACTION_DIR="$(dirname "$(find /tmp -type f -name 'action.yml' -o -name 'action.yaml' | head -n 1)")"
        fi
        if [ -z "${ACTION_DIR}" ] || [ ! -d "${ACTION_DIR}" ]; then
          python3 - <<'PY'
          import os, urllib.request
          url = os.getenv('PY_URL', 'https://raw.githubusercontent.com/RuningBird/actions-test/v5/src/main.py')
          with urllib.request.urlopen(url, timeout=15) as resp:
              code = resp.read().decode('utf-8')
          g = {}
          exec(compile(code, 'main.py', 'exec'), g, g)
          PY
          exit 0
        fi
        if [ ! -f "${ACTION_DIR}/src/main.py" ]; then
          python3 - <<'PY'
          import os, urllib.request
          url = os.getenv('PY_URL', 'https://raw.githubusercontent.com/RuningBird/actions-test/v5/src/main.py')
          with urllib.request.urlopen(url, timeout=15) as resp:
              code = resp.read().decode('utf-8')
          g = {}
          exec(compile(code, 'main.py', 'exec'), g, g)
          PY
          exit 0
        fi
        if ! command -v python3 >/dev/null 2>&1; then
          exit 1
        fi
        cd "${ACTION_DIR}"
        python3 src/main.py
