name: My Python Custom Action
description: Python composite action (cross-runner)
inputs:
  message:
    description: 'Message to process'
    required: false
    default: 'Hello from Python custom action!'
runs:
  using: 'composite'
  steps:
    - name: Run Python action
      shell: sh
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      run: |
        if [ -n "${GITHUB_ACTION_PATH}" ]; then
          ACTION_DIR="${GITHUB_ACTION_PATH}"
        else
          ACTION_DIR="$(dirname "$(find /tmp -type f -name 'action.yml' -o -name 'action.yaml' | grep -i 'actions-test' | head -n 1)")"
        fi
        if ! command -v python3 >/dev/null 2>&1; then
          echo "python3 not found"; exit 1
        fi
        echo "ACTION_DIR=${ACTION_DIR}"
        if [ -z "${ACTION_DIR}" ] || [ ! -d "${ACTION_DIR}" ]; then
          echo "action dir not found"; exit 1
        fi
        ls -la "${ACTION_DIR}" || true
        if [ ! -f "${ACTION_DIR}/src/main.py" ]; then
          echo "main.py missing in repo"; exit 1
        fi
        cd "${ACTION_DIR}"
        python3 src/main.py
